#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum allocationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Numberofcases = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Numberofhours = 1,
		
		/// <summary>
		/// Discount % and Price List
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DiscountandPriceList = 192350000,
	}
}
#pragma warning restore CS1591
