#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Type of  channel activities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum convertrule_channelactivity
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SocialActivity = 4216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teamschat = 10254,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InviteRedemption = 10414,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortalComment = 10415,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicealert = 10726,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyinvite = 10741,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicesurveyresponse = 10744,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversation = 10842,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Session = 10859,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotTranscript = 11120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingAlert = 11288,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outboundmessage = 11488,
	}
}
#pragma warning restore CS1591
