#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// List of Mobile Offline Enabled Entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum mobileofflineenabledentities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Note = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueItem = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAKPIInstance = 9752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityFileAttachment = 10253,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleImage = 10262,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleAttachment = 10268,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_historicalcaseharvestbatch = 10274,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_historicalcaseharvestrun = 10275,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InterimUpdateKnowledgeArticle = 10276,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleCustomEntity = 10277,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeHarvestJobRecord = 10278,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncFnoState = 10304,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncState = 10305,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImageDescriptor = 1007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerPagesDDOSAlert = 10458,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountLeads = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContactLeads = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lead = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Product = 1024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Property = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyAssociation = 1235,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyOptionSetItem = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceList = 1022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceListItem = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductRelationship = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unit = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnitGroup = 1056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entitlement = 9700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementContact = 7272,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementProduct = 6363,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementTemplateProduct = 4545,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentKnowledgeBaseRecord = 9931,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneToCaseProcess = 952,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connection = 3234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionRole = 3231,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlert = 10514,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDevice = 10515,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCategory = 10516,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCommand = 10517,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCommandDefinition = 10518,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceDataHistory = 10519,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceProperty = 10520,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceRegistrationHistory = 10521,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTPropertyDefinition = 10524,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTProvider = 10525,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTProviderInstance = 10526,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTSettings = 10527,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlerttoCaseProcess = 10530,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorAddress = 1004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorProduct = 1006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadCompetitors = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadProduct = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadToOpportunitySalesProcess = 954,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Opportunity = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityCompetitors = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunitySalesProcess = 953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Competitor = 123,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyInstance = 1333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invoice = 1090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvoiceProduct = 1091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quote = 1084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Order = 1088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Currency = 9105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Shorturl = 10739,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductMap = 10762,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityAttachment = 10786,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_globalrulesetconfiguration = 10804,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_broadcastmessagebulkactionapiprivilege = 10928,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_bulkassigntoqueueapiprivilege = 10929,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_bulkforcecloseapiprivilege = 10930,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_notifyagentbulkactionapiprivilege = 10932,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChannelProfile = 11059,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DispositionCodeCategory = 11067,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copilotknowledgeinteraction = 11119,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EvaluationGlobalConfig = 11170,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PAFlowRunTracker = 11178,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountResearchAgentTrigger = 11188,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountResearchResult = 11189,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorResearchAgentTrigger = 11190,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadAgentResult = 11193,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadDelinkResult = 11194,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutreachAgentResult = 11196,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutreachTriggerAgent = 11197,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QualificationAgentTrigger = 11198,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesAgentUsage = 11200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StakeholderResearchOutput = 11201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SummarySynthesizerAgentTrigger = 11203,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TargetCustomerProfilePrefillAgentResult = 11204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TargetCustomerProfilePrefillAgentTrigger = 11205,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityRankerMapping = 11208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityResearchIndicator = 11210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityResearchUserInteractions = 11212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RCSWatermark = 11213,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity73b3401912 = 11214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityfc0c4d5270 = 11234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity3e947fb752 = 11252,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SchedulingParameter = 11306,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InspectionTemplate = 11318,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InspectionAttachment = 11319,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InspectionTemplateVersion = 11320,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrderLine = 1089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteLine = 1085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InspectionResponse = 11322,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PurchaseOrderBusinessProcess = 11347,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CasetoWorkOrderBusinessProcess = 11348,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgreementBusinessProcess = 11349,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderBusinessProcess = 11350,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityLine = 1083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentTypesSetup = 11361,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookableResource = 1150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookableResourceBooking = 1145,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingStatus = 1152,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticle = 9953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleViews = 9955,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AssetCategoryTemplateAssociation = 10490,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AssetTemplateAssociation = 10491,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookableResourceBookingQuickNote = 11408,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingTimestamp = 11346,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerAsset = 10492,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerAssetCategory = 10496,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldServicePriceListItem = 11352,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldServiceSetting = 11353,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FunctionalLocation = 10497,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FunctionalLocationType = 10498,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentType = 11356,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentTypeProduct = 11358,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentTypeResolution = 11414,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentTypeService = 11359,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentTypeServiceTask = 11360,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LocationTemplateAssociation = 10499,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FunctionalLocationTypeTemplateAssociation = 10500,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nottoexceed = 11416,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Priority = 11294,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductInventory = 11375,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyDefinition = 10501,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyAssetAssociation = 10502,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyLocationAssociation = 10503,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyLog = 10504,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyTemplateAssociation = 10505,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolution = 11419,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceTaskType = 11394,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TaxCode = 11331,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TemplateForProperties = 10506,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeEntry = 11323,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeSource = 11324,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TimeOffRequest = 11395,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trade = 11420,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Warehouse = 11333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrder = 11397,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderIncident = 11400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workordernottoexceed = 11424,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderProduct = 11401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderResolution = 11425,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderService = 11403,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderServiceTask = 11404,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderSubstatus = 11405,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderType = 11406,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Territory = 2013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CFSIoTAlertProcessFlow = 11426,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GeolocationSettings = 11427,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MobileSource = 11433,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebEngagementRuleset = 11448,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebEngagementRulesetConfig = 11449,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WebEngagementRulesetRevision = 11450,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomNeuralVoice = 11456,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountResearchSummaryTrigger = 11553,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAccountInsightsResult = 11554,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomizationAgentTrigger = 11555,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomOOBResearchResult = 11556,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultOOBAccountResearchResult = 11557,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesCompanyResolverLeadTrigger = 11558,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelatedConversationTriggerTable = 11559,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity1b6eac6f1b = 11560,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity40c93ffc4c = 11578,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity1f908fe2e0 = 11600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitycba209a464 = 11618,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CRMActivityMapping = 11635,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitydd388a70f5 = 11637,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity786e65f070 = 11651,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BotVariable = 11672,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity895b1d1c7f = 11673,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityb5c0450faf = 11690,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitye9892ad114 = 11707,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity2d3001f502 = 11713,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity973b902839 = 11714,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity5035f2c9c0 = 11715,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitycdd261fa63 = 11719,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityc02d670ecb = 11725,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity41e3c36781 = 11729,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity42acb2fa93 = 11732,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity925d974c6b = 11734,
	}
}
#pragma warning restore CS1591
