#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_optimizationstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Running = 772020000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Succeeded = 772020001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 772020002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 772020003,
	}
}
#pragma warning restore CS1591
