#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Shows billing status of transactions.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_billingstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workorderclosedposted = 690970000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnbilledSalesCreated = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerInvoiceCreated = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerInvoicePosted = 192350002,
		
		/// <summary>
		/// Canceled billing status of transactions.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 192350003,
	}
}
#pragma warning restore CS1591
