#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Copilot product type picker
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_vivacopilottype
	{
		
		/// <summary>
		/// Represents records related to Sales Copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		M365CopilotSales = 10000,
		
		/// <summary>
		/// Represents records related to Service Copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		M365CopilotService = 10001,
		
		/// <summary>
		/// Represents records that are shared across different Copilot types
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Shared = 11000,
	}
}
#pragma warning restore CS1591
