#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Time Entry Generation Strategy
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_timeentrygenerationstrategy
	{
		
		/// <summary>
		/// Select this option to manually generate time entries of bookings.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Manual = 192355200,
		
		/// <summary>
		/// Select this option in order for the system to automatically generate time entries based on booking timestamps.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutoGeneratefromBookingTimestamps = 192355201,
	}
}
#pragma warning restore CS1591
