#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Communication Provider
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_occommunicationprovider
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AzureCommunicationServices = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twilio = 192350001,
		
		/// <summary>
		/// TeleSign SMS provider
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TeleSign = 192350002,
		
		/// <summary>
		/// Microsoft Teams Phone System Provider
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftTeamsPhoneSystem = 192350003,
	}
}
#pragma warning restore CS1591
