#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Frequency at which timestamps are generated
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_timestampfrequency
	{
		
		/// <summary>
		/// Per Booking Status Change
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PerBookingStatusChange = 192350000,
		
		/// <summary>
		/// Per Field Service Status Change
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PerFieldServiceStatusChange = 192350001,
	}
}
#pragma warning restore CS1591
