#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_bookingsource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ScheduleBoard = 690970001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mobile = 690970002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Manual = 690970003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ScheduleAssistant = 690970004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemAgreementSchedule = 690970005,
	}
}
#pragma warning restore CS1591
