#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Sequence Step Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_sequencestep_type
	{
		
		/// <summary>
		/// Simple Condition Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SimpleCondition = 1,
		
		/// <summary>
		/// Task Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		/// <summary>
		/// Text message step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Textmessage = 4213,
		
		/// <summary>
		/// Email Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		/// <summary>
		/// Phone call step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Phonecall = 4210,
		
		/// <summary>
		/// Wait Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wait = 0,
		
		/// <summary>
		/// Automated Email step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutomatedEmail = 3,
		
		/// <summary>
		/// Automatic action step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Autoaction = 4,
		
		/// <summary>
		/// LinkedIn action step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LinkedInaction = 5,
		
		/// <summary>
		/// Automated text message step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Automatedtextmessage = 6,
		
		/// <summary>
		/// Automated Experimentation step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutomatedExperimentation = 7,
		
		/// <summary>
		/// EmailValidation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailValidation = 8,
		
		/// <summary>
		/// Research
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Research = 9,
		
		/// <summary>
		/// Outreach
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outreach = 10,
		
		/// <summary>
		/// Engage
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Engage = 11,
		
		/// <summary>
		/// Competitor
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Competitor = 12,
		
		/// <summary>
		/// Stakeholder
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Stakeholder = 13,
		
		/// <summary>
		/// Handover
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Handover = 14,
	}
}
#pragma warning restore CS1591
