#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Crew Strategy used in crew management
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_crewstrategy
	{
		
		/// <summary>
		/// Crew Leader Management
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CrewLeaderManagement = 192350001,
		
		/// <summary>
		/// Crew Member Self-Management
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CrewMemberSelfManagement = 192350002,
		
		/// <summary>
		/// Cascade and Accept Cascade Completely (Not Recommended)
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CascadeandAcceptCascadeCompletely_NotRecommended = 192350000,
	}
}
#pragma warning restore CS1591
