#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdynmkt_channelconsentresolutionoverrides
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nooverride = 238550000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Usecustomapitoresolve = 238550001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Alwaysresolvetoconsentgiven = 238550002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Alwaysresolvetoconsentnotgiven = 238550003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UseRealtimejourneysdefaultimplementation = 238550004,
	}
}
#pragma warning restore CS1591
