#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdynmkt_source
	{
		
		/// <summary>
		/// Internal – Created manually or changed in the application
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Internal = 534120000,
		
		/// <summary>
		/// Preference page - updated by customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Preferencepage = 534120001,
		
		/// <summary>
		/// Text message - updated by customer via text message
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Textmessage = 534120002,
	}
}
#pragma warning restore CS1591
