#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// behaviour of the solution
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_solutionbehaviour
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Global = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Intent = 100000001,
	}
}
#pragma warning restore CS1591
