#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Indicates the origin of the not-to-exceed amount.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_ntesource
	{
		
		/// <summary>
		/// Indicates not-to-exceed amount was based on a pre-negotiated not-to-exceed threshold.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Nottoexceed = 192350100,
		
		/// <summary>
		/// Indicates not-to-exceed amount was based on custom amount specified by the user.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Userspecified = 192350200,
		
		/// <summary>
		/// Indicates not-to-exceed amount was based on an approved quotation.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approvedquote = 192350300,
	}
}
#pragma warning restore CS1591
