#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_streamsource
	{
		
		/// <summary>
		/// Connect with customers via Live chat channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Livechat = 192360000,
		
		/// <summary>
		/// Connect with customers via Voice channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voice = 192370000,
		
		/// <summary>
		/// Connect with customers via Video channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Video = 192380000,
		
		/// <summary>
		/// Connect with customers via Co-browse channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cobrowse = 192390000,
		
		/// <summary>
		/// Connect with customers via Screen sharing channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Screensharing = 192400000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRecords = 192350000,
		
		/// <summary>
		/// Connect with customers via SMS channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SMS = 192340000,
		
		/// <summary>
		/// Connect with customers via Facebook channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 192330000,
		
		/// <summary>
		/// Connect with customers via LINE channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LINE = 192310000,
		
		/// <summary>
		/// Connect with customers via WhatsApp channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WhatsApp = 192300000,
		
		/// <summary>
		/// Connect with customers via WeChat channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WeChat = 192320000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twitter = 192350001,
		
		/// <summary>
		/// Connect with customers via Custom channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Custom = 192350002,
		
		/// <summary>
		/// Connect with customers via Apple Messages for Business channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AppleMessagesforBusiness = 192450000,
		
		/// <summary>
		/// Connect with customers via Google's Business Messages channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GooglesBusinessMessages = 192450001,
		
		/// <summary>
		/// Connect with customers via Teams channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftTeams = 19241000,
	}
}
#pragma warning restore CS1591
