#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_widgetthemecolor
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Red = 19236001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teal = 192360017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Blue = 19236002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Green = 19236003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Black = 19236004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Orange = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pink = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Grey = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Violet = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Brown = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Clay = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Purple = 192350007,
	}
}
#pragma warning restore CS1591
