#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_transactionclassification
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Commission = 690970000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Additional = 690970001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tax = 690970002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Time = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Expense = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Material = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Milestone = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fee = 192350004,
	}
}
#pragma warning restore CS1591
