#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Time Cost Actuals Source
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_timecostactualssource
	{
		
		/// <summary>
		/// Booking Journals on Post of Work Order
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BookingJournalsonPostofWorkOrder = 192354000,
		
		/// <summary>
		/// Work Order Time Entry Approval
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrderTimeEntryApproval = 192354001,
	}
}
#pragma warning restore CS1591
