#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Source of the Review status of Intent or Intent Group
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_intentreviewstate_source
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AIGenerated = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AdminUpdated = 192350002,
	}
}
#pragma warning restore CS1591
