#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_serviceappointmentstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pending = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserved = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Arrived = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoShow = 10,
	}
}
#pragma warning restore CS1591
