#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_parametertype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StringList = 690970000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Json = 690970001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Xml = 690970002,
	}
}
#pragma warning restore CS1591
