#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_transactiontypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cost = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProjectContract = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnbilledSales = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BilledSales = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResourcingUnitCost = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InterOrganizationalSales = 192350008,
	}
}
#pragma warning restore CS1591
