#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_fieldserviceautonumberingentities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrder = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agreement = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryAdjustment = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InventoryTransfer = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PurchaseOrder = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RMA = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RTV = 6,
	}
}
#pragma warning restore CS1591
