#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Defines the repeat of booking by a daily, weekly, monthly or yearly frequency
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_recurrencepattern
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Daily = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Weekly = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Monthly = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yearly = 192350003,
	}
}
#pragma warning restore CS1591
