#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// The type of time entry
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_timeentrytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Overtime = 192354320,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Work = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Absence = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Vacation = 192350002,
		
		/// <summary>
		/// On Break
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnBreak = 192355000,
		
		/// <summary>
		/// Travel
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Travel = 192355001,
	}
}
#pragma warning restore CS1591
