#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Used to identify the type of dependency that the requirements need to satisfy
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_requirementdependencytype
	{
		
		/// <summary>
		/// Used when the dependent requirement needs to start after the end of the other requirement.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StartAfterEnd = 192350000,
	}
}
#pragma warning restore CS1591
