#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Defines the months in a year
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_monthofyear
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		January = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		February = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		March = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		April = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		May = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		June = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		July = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		August = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		September = 192350008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		October = 192350009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		November = 192350010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		December = 192350011,
	}
}
#pragma warning restore CS1591
