#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_numberofdays
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_0 = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_15 = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_30 = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_60 = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_90 = 192350004,
	}
}
#pragma warning restore CS1591
