#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdynmkt_doijobstatus_optionset
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RequestAccepted = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailCreated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailPublished = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyCreated = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyPublishingStarted = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyPublished = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProcessingCompleted = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailCreateFailed = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EmailPublishFailed = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyCreateFailed = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JourneyPublishFailed = 11,
	}
}
#pragma warning restore CS1591
