#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// The last session outcome options.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_lastsessionoutcome
	{
		
		/// <summary>
		/// Indicates that there was no session outcome.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 419570000,
		
		/// <summary>
		/// Indicates that the last session was abandoned.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Abandoned = 419570001,
		
		/// <summary>
		/// Indicates that the last session was escalated.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Escalated = 419570002,
		
		/// <summary>
		/// Indicates that the last session was resolved.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolved = 419570003,
	}
}
#pragma warning restore CS1591
