#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Booking Status Optimization Methods
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_bookingstatusoptimizationmethod
	{
		
		/// <summary>
		/// Bookings in this status can be optimized by the optimization engine
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Optimize = 192350000,
		
		/// <summary>
		/// Bookings in this status will not be moved by the optimization engine
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DoNotMove = 192350001,
		
		/// <summary>
		/// Bookings in this status will be completely ignored by the optimization engine
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ignore = 192350002,
	}
}
#pragma warning restore CS1591
