#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// The status of the quality agent.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_qualityagentstatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pending = 700610000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inprogress = 700610001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 700610002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Error = 700610003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notapplicable = 700610004,
	}
}
#pragma warning restore CS1591
