#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Select whether the Bookable Resource Type Pool is of Account. Contact or User.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_pooltype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Equipment = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facility = 192350004,
	}
}
#pragma warning restore CS1591
