#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyusd_enabletrigger
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Always = 803750000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerSession = 803750001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ScriptExpression = 803750002,
	}
}
#pragma warning restore CS1591
