#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Indicates type of crew member
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_crewmembertype
	{
		
		/// <summary>
		/// Crew's Leader
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Leader = 192350000,
		
		/// <summary>
		/// Crew's member
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Member = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 192350002,
	}
}
#pragma warning restore CS1591
