#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Type of not-to-exceed amount.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_ntetype
	{
		
		/// <summary>
		/// Indicates not-to-exceed amount for Customer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Price = 192350100,
		
		/// <summary>
		/// Indicates not-to-exceed amount for Costs from vendors.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cost = 192350200,
		
		/// <summary>
		/// Indicates not-to-exceed amount for Price, and Cost based on specifed margin from Price.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Priceandcostmargin = 192350300,
	}
}
#pragma warning restore CS1591
