#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// The last session outcome reason options.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_lastsessionoutcomereason
	{
		
		/// <summary>
		/// Indicates a no error found.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoError = 419580000,
		
		/// <summary>
		/// Indicates an error from the user
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserError = 419580001,
		
		/// <summary>
		/// Indicates that a system error occurred.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SystemError = 419580002,
		
		/// <summary>
		/// Indicates a normal session user exit.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UserExit = 419580003,
		
		/// <summary>
		/// Indicates an agent transfer without errors.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentTransferWithoutError = 419580004,
		
		/// <summary>
		/// Indicates that an actual user of the Bot decides to raise an agent transfer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentTransferRequestedByUser = 419580005,
		
		/// <summary>
		/// Indicates an exit due to issue resolution.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolved = 419580006,
		
		/// <summary>
		/// Indicates that a creator or author of the Bot configures the bot to transfer to an agent.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentTransferConfiguredByAuthor = 419580007,
		
		/// <summary>
		/// Indicates that in Question node maximum attempts are reached but Bot could not help and proposes to transfer to an agent.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentTransferFromQuestionMaxAttempts = 419580008,
	}
}
#pragma warning restore CS1591
