#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Shows the status of time entry records.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_timeentrystatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Returned = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Submitted = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelled = 192354320,
	}
}
#pragma warning restore CS1591
