#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Ordering of teams for scheduling a requirement group.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_requirementgrouporder
	{
		
		/// <summary>
		/// Sort by the number of resources needed to satisfy the set of requirements in ascending order.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FewestResourcesFirst = 690970000,
		
		/// <summary>
		/// Sort by the earliest start time.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EarliestTimeFirst = 690970001,
	}
}
#pragma warning restore CS1591
