#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_salesmicroagenttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ResearchAgent = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutreachAgent = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EngageAgent = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadReadinessAgent = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DCA_ResearchAgent = 5,
		
		/// <summary>
		/// Microagent that handles the Handover process for Sales Agent.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HandoverMicroagent = 6,
		
		/// <summary>
		/// DCA that handles the outreach emails.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DCAOutreachagent = 7,
		
		/// <summary>
		/// DCA that handles the customer engagement.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DCAEngageagent = 8,
		
		/// <summary>
		/// Email validation agent
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Emailvalidationagent = 9,
	}
}
#pragma warning restore CS1591
