#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_actiontype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Proposeaknowledgearticle = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolvecase = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sendnextfollowup = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Replytocustomer = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Replytocustomer1 = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Suggestaresolution = 100000005,
	}
}
#pragma warning restore CS1591
