#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_opportunityresearchtopicchoice
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealOverview = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealRisk = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealImportance = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealHealth = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NeedsandPainPoints = 100000004,
		
		/// <summary>
		/// Stakeholder Insights
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StakeholderInsights = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountInsights = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KeyDealInsights = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KeyUpdates = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorInsights = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelatedConversationMapping = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealSummary = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChainOfThoughts = 100000012,
	}
}
#pragma warning restore CS1591
