#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Various scenario types
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_scenariotype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Askaquestion = 100230201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Liveconversationresponse = 100230202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Writeanemail = 100230203,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copilot = 100230204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Casesummary = 100230205,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Liveconversationsummary = 100230206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Timelinehighlights = 100230207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Knowledgedraftassist = 100230208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customentitysummary = 100230209,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CollaboratewithSMEs = 100230210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InlineCopilotforemail = 100230211,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Timelinenextbestactions = 100230212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IntentAssist = 100230213,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		knowledgeharvest = 100230214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolutionnotes = 100230215,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChatAssist = 100230216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teamscollaborationsummary = 100230217,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutonomousCaseCreateandUpdate = 100230218,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProactiveInsights = 100230219,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QualityEvaluation = 100230220,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enrichrecord = 100230321,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolvecase = 100230322,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CaseFollowUp = 100230323,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CaseClosure = 100230324,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Workload = 100230325,
	}
}
#pragma warning restore CS1591
