#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Defines a booking recurrence that occurs on specific weekday
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_recurrenceday
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Day = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Weekday = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WeekendDay = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sunday = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Monday = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Tuesday = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Wednesday = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Thursday = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Friday = 192350008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Saturday = 192350009,
	}
}
#pragma warning restore CS1591
