#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// An option set to distinguish between project service lines and field service lines
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_linetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProjectServiceLine = 690970000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FieldServiceLine = 690970001,
	}
}
#pragma warning restore CS1591
