#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_chatquestionnairetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prechatauthenticated = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Prechatunauthenticated = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Offlineauthenticated = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Offlineunauthenticated = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Postchatauthenticated = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Postchatunauthenticated = 192350005,
	}
}
#pragma warning restore CS1591
