#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdynmkt_reason
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noreasons = 534119999,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptinAdvertisement = 534120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptinLandingpage = 534120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptinEvents = 534120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutContentwasirrelevant = 534120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutReceivedtoofrequently = 534120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutDidntrecallsigningup = 534120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutPrivacyconcerns = 534120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OptoutOneclickunsubscribe = 534120007,
	}
}
#pragma warning restore CS1591
