#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Select the entity for which SLA is to be created
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum sla_slaenabledentities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Order = 1088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lead = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quote = 1084,
	}
}
#pragma warning restore CS1591
