#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPDSDemo.Entities
{
	
	
	/// <summary>
	/// Options for Template Default View
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum templatedefaultview
	{
		
		/// <summary>
		/// Tiles View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TilesView = 1,
		
		/// <summary>
		/// Grid View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GridView = 2,
		
		/// <summary>
		/// List View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ListView = 3,
	}
}
#pragma warning restore CS1591
