# =============================================================================
# Composite Action: Copy Plugin Packages
# =============================================================================
# Copies built plugin packages (.nupkg) to the solution's pluginpackages folders
# so they can be packed into the solution. Handles the naming convention
# differences between build output and PAC CLI expectations.
#
# IMPORTANT: This action is for Plugin Packages (NuGet-based), NOT Plugin
# Assemblies (classic DLLs). These are different components with different
# folder structures and naming conventions.
#
# See: docs/reference/PLUGIN_COMPONENTS_REFERENCE.md
#
# Prerequisites:
#   - Must build the solution first using build-solution action
#   - Solution must already have pluginpackages folders (from export)
#
# Usage:
#   - name: Copy plugin packages
#     uses: ./.github/actions/copy-plugin-packages
#     with:
#       source-package: src/PluginPackages/PPDSDemo.PluginPackage/bin/Release/PPDSDemo.PluginPackage.1.0.0.nupkg
#       solution-folder: solutions/PPDSDemo/src
#
# Naming Convention:
#   Build output:    PPDSDemo.PluginPackage.1.0.0.nupkg
#   Solution expects: ppds_PPDSDemo.PluginPackage.nupkg (in package/ subfolder)
#
#   Transform: Add publisher prefix (from folder name), remove version
#
# =============================================================================

name: 'Copy Plugin Packages'
description: 'Copy built plugin packages (.nupkg) to solution folder for packing'

inputs:
  source-package:
    description: 'Path to built plugin package (.nupkg file)'
    required: true
  solution-folder:
    description: 'Base path to unpacked solution (e.g., solutions/PPDSDemo/src)'
    required: true
  copy-to-managed:
    description: 'Copy to Managed subfolder'
    required: false
    default: 'true'
  copy-to-unmanaged:
    description: 'Copy to Unmanaged subfolder'
    required: false
    default: 'true'
  copy-to-root:
    description: 'Copy to root pluginpackages folder (if exists)'
    required: false
    default: 'true'

outputs:
  copied-count:
    description: 'Number of locations where package was copied'
    value: ${{ steps.copy.outputs.copied_count }}
  target-paths:
    description: 'Paths where package was copied (newline-separated)'
    value: ${{ steps.copy.outputs.target_paths }}
  package-id:
    description: 'Extracted package ID (without version)'
    value: ${{ steps.names.outputs.package_id }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      id: validate
      shell: bash
      run: |
        if [ ! -f "${{ inputs.source-package }}" ]; then
          echo "::error::Source package not found: ${{ inputs.source-package }}"
          exit 1
        fi

        if [ ! -d "${{ inputs.solution-folder }}" ]; then
          echo "::error::Solution folder not found: ${{ inputs.solution-folder }}"
          exit 1
        fi

        # Validate it's a .nupkg file
        if [[ "${{ inputs.source-package }}" != *.nupkg ]]; then
          echo "::error::Source file must be a .nupkg file: ${{ inputs.source-package }}"
          exit 1
        fi

        echo "Source package: ${{ inputs.source-package }}"
        echo "Solution folder: ${{ inputs.solution-folder }}"

    - name: Extract package ID
      id: names
      shell: bash
      run: |
        # Get source package filename
        SOURCE_FILE=$(basename "${{ inputs.source-package }}")
        echo "Source filename: $SOURCE_FILE"

        # Extract package ID by removing version and .nupkg extension
        # Pattern: PackageName.X.Y.Z.nupkg -> PackageName
        # Use regex to strip semantic version pattern
        # PPDSDemo.PluginPackage.1.0.0.nupkg -> PPDSDemo.PluginPackage
        PACKAGE_ID=$(echo "$SOURCE_FILE" | sed -E 's/\.[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?\.nupkg$//')

        if [ -z "$PACKAGE_ID" ]; then
          echo "::error::Could not extract package ID from filename: $SOURCE_FILE"
          exit 1
        fi

        echo "Package ID: $PACKAGE_ID"
        echo "package_id=$PACKAGE_ID" >> $GITHUB_OUTPUT

    - name: Copy packages
      id: copy
      shell: bash
      env:
        SOURCE: ${{ inputs.source-package }}
        SOLUTION_FOLDER: ${{ inputs.solution-folder }}
        PACKAGE_ID: ${{ steps.names.outputs.package_id }}
        COPY_MANAGED: ${{ inputs.copy-to-managed }}
        COPY_UNMANAGED: ${{ inputs.copy-to-unmanaged }}
        COPY_ROOT: ${{ inputs.copy-to-root }}
      run: |
        set -euo pipefail

        COPIED_COUNT=0
        TARGET_PATHS=""

        copy_to_location() {
          local base_path="$1"
          local location_name="$2"

          # Find pluginpackages folder matching our package ID
          # Pattern: *_PackageID (e.g., ppds_PPDSDemo.PluginPackage)
          local package_folders=$(find "$base_path" -maxdepth 1 -type d -name "*_${PACKAGE_ID}" 2>/dev/null || echo "")

          if [ -z "$package_folders" ]; then
            echo "No matching pluginpackages folder found in $location_name for package: $PACKAGE_ID"
            return
          fi

          for folder in $package_folders; do
            # Target is in the 'package' subfolder
            local package_subfolder="$folder/package"

            if [ ! -d "$package_subfolder" ]; then
              echo "::warning::package/ subfolder not found in $folder, creating it"
              mkdir -p "$package_subfolder"
            fi

            # Derive target filename from folder name (folder name + .nupkg)
            local folder_name=$(basename "$folder")
            local target_name="${folder_name}.nupkg"
            local target_path="$package_subfolder/$target_name"

            echo "Copying to: $target_path"
            cp "$SOURCE" "$target_path"

            if [ -f "$target_path" ]; then
              COPIED_COUNT=$((COPIED_COUNT + 1))
              TARGET_PATHS="${TARGET_PATHS}${target_path}\n"
              echo "Successfully copied to $location_name"
            fi
          done
        }

        # Copy to Managed folder
        if [ "$COPY_MANAGED" = "true" ]; then
          if [ -d "$SOLUTION_FOLDER/Managed/pluginpackages" ]; then
            copy_to_location "$SOLUTION_FOLDER/Managed/pluginpackages" "Managed"
          else
            echo "Managed/pluginpackages folder not found"
          fi
        fi

        # Copy to Unmanaged folder
        if [ "$COPY_UNMANAGED" = "true" ]; then
          if [ -d "$SOLUTION_FOLDER/Unmanaged/pluginpackages" ]; then
            copy_to_location "$SOLUTION_FOLDER/Unmanaged/pluginpackages" "Unmanaged"
          else
            echo "Unmanaged/pluginpackages folder not found"
          fi
        fi

        # Copy to root pluginpackages folder (if exists)
        if [ "$COPY_ROOT" = "true" ]; then
          if [ -d "$SOLUTION_FOLDER/pluginpackages" ]; then
            copy_to_location "$SOLUTION_FOLDER/pluginpackages" "Root"
          else
            echo "Root pluginpackages folder not found"
          fi
        fi

        echo ""
        echo "=== Copy Summary ==="
        echo "Package ID: $PACKAGE_ID"
        echo "Copied to $COPIED_COUNT location(s)"

        echo "copied_count=$COPIED_COUNT" >> $GITHUB_OUTPUT

        # Multi-line output
        {
          echo "target_paths<<EOF"
          echo -e "$TARGET_PATHS"
          echo "EOF"
        } >> $GITHUB_OUTPUT

        if [ $COPIED_COUNT -eq 0 ]; then
          echo "::warning::No packages were copied. Ensure pluginpackages folders exist and contain matching package folders."
        fi

    - name: Generate step summary
      shell: bash
      env:
        COPIED_COUNT: ${{ steps.copy.outputs.copied_count }}
        TARGET_PATHS: ${{ steps.copy.outputs.target_paths }}
        SOURCE: ${{ inputs.source-package }}
        PACKAGE_ID: ${{ steps.names.outputs.package_id }}
      run: |
        echo "## Plugin Package Copy" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Source | \`$(basename "$SOURCE")\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Package ID | \`$PACKAGE_ID\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Copied To | $COPIED_COUNT location(s) |" >> $GITHUB_STEP_SUMMARY

        if [ -n "$TARGET_PATHS" ]; then
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Target Locations" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo -e "$TARGET_PATHS" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        fi
